apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-06-05T05:34:03Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: production-rabbitmqcluster
    app.kubernetes.io/part-of: rabbitmq
  name: persistence-production-rabbitmqcluster-server-1
  namespace: default
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: false
    controller: true
    kind: RabbitmqCluster
    name: production-rabbitmqcluster
    uid: cf78ae05-c532-4ade-aa95-fd53c627dd4e
  resourceVersion: "316527"
  uid: 8970f5ed-617e-4dfb-91f7-4420f8e213f2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rabbit-operator-pv-volume
  volumeMode: Filesystem
  volumeName: rabbit-operator-pv-volume-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
