apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-operator-pv-0
  labels:
    type: local
spec:
  storageClassName: storage-class-rabbit-operator
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/rabbitOperatorDisk-0"

    #Usar como plantilla para crear los necesarios