apiVersion: v1
kind: Service
metadata:
  name: frontend-store
spec:
  type: NodePort
  selector:
    app: node-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001