apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: frontend-full
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: frontend-full
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-full
  template:
    metadata:
      labels:
        app: frontend-full
    spec:
      containers:
        - name: front-kenyi
          image: kenyialcantara/store:1.3
          ports:
            - name: rabbitmq-port
              containerPort: 3000
            - name: mysql-port
              containerPort: 3001
          env:
            - name: QUEUE_NAME
              value: "python-java"
            - name: BACK_HOST 
              value: 10.97.235.155
            - name: BACK_PORT
              value: "3000"